version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      github_actions-minor-patch:
        update-types: [minor, patch]
  - package-ecosystem: cargo
    directories:
      - "/"
      - "/engine"
      - "/engine/fuzz"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      cargo-minor-patch:
        update-types: [minor, patch]
  - package-ecosystem: docker
    directories:
      - "/deploy/dev"
      - "/deploy/docker"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      docker-minor-patch:
        update-types: [minor, patch]
  - package-ecosystem: gomod
    directories:
      - "/"
      - "/operator"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      gomod-minor-patch:
        update-types: [minor, patch]
  - package-ecosystem: helm
    directories:
      - "/deploy/helm/nexora"
      - "/deploy/helm/nexora-operator"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      helm-minor-patch:
        update-types: [minor, patch]
  - package-ecosystem: npm
    directory: "/web"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      npm-minor-patch:
        update-types: [minor, patch]
