package e2e

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"google.golang.org/protobuf/proto"

	"github.com/piwi3910/nexora/e2e/harness"
	controlv1 "github.com/piwi3910/nexora/gen/go/nexora/control/v1"
)

func init() { registerGUISeed(seedAIForecasts) }

// insertForecastSQL seeds the upstream prediction, for which no create API exists.
// Capacity below is generated by the real agent from telemetry and daily history.
const insertForecastSQL = `INSERT INTO ai_forecasts (kind, subject, detail, generated_at, valid_until)
VALUES ($1, $2, $3::jsonb, now() - interval '3 hours', now() + interval '6 hours')`

// seedAIForecasts supplies an upstream prediction and a recursor-cache growth series.
// The capacity agent runs here and again in screen 50, using the same measured
// bytes and paired engine budget. Screen 55 must still display exactly 12 days.
func seedAIForecasts(s guiSeedEnv) {
	var ups []struct {
		ID   string `json:"id"`
		Name string `json:"name"`
	}
	s.Admin.Must("GET", "/upstreams", nil, &ups, 200)
	id := ""
	for _, u := range ups {
		if u.Name == "fixture" {
			id = u.ID
		}
	}
	if id == "" {
		s.T.Fatalf("no fixture upstream to forecast: %+v", ups)
	}

	upstream, err := json.Marshal(map[string]any{
		"upstream_id": id, "upstream_name": "fixture", "trend": "degrading", "confidence": 0.78,
		"current_rtt_p50_ms": 120.0, "current_rtt_p99_ms": 350.0, "slope_ms_per_hour": 4.5,
		"step_change": false, "periodic_hours": []int{}, "projected_time_to_threshold": nil,
		"data_points_analyzed": 288,
		"reasoning":            "The p99 of fixture rose from 90 ms to 350 ms over the last 24 hours.",
		"recommendation": map[string]any{"type": "switch_strategy",
			"description": "Switch the upstream strategy to fastest so the slow upstream stops deciding answers."},
	})
	if err != nil {
		s.T.Fatalf("marshal upstream forecast: %v", err)
	}
	harness.PGExec(s.T, s.PGURL, insertForecastSQL, "upstream", id, string(upstream))

	seedGUIRecursorCapacity(s)

	s.Vars["NEXORA_E2E_AI_UPSTREAM_FORECAST"] = id
}

func seedGUIRecursorCapacity(s guiSeedEnv) {
	// A dedicated, disconnected telemetry engine cannot have its newest report
	// replaced by live fixture heartbeats. Its group keeps it out of live rollouts.
	group := s.Admin.CreateEngineGroup(map[string]any{"name": "gui-capacity-telemetry"})
	engineID := uuid.NewString()
	harness.PGExec(s.T, s.PGURL, `insert into engines(id, node_name, certificate_serial, engine_group_id)
		values ($1, 'gui-capacity-telemetry', 'gui-capacity-telemetry', $2)`, engineID, group.ID)
	const current, growth, limit = 18_500_000, 350_000, 22_700_000
	// All dates use the sampler's UTC day, including on non-UTC database hosts.
	today, err := time.Parse(time.DateOnly, pgText(s.T, s.PGURL,
		`select (now() at time zone 'UTC')::date::text`))
	if err != nil {
		s.T.Fatal(err)
	}
	for daysAgo := 6; daysAgo >= 1; daysAgo-- {
		harness.PGExec(s.T, s.PGURL, `insert into ai_capacity_samples(day, resource, value, limit_value)
			values ($1, 'recursor_cache', $2, $3)`, today.AddDate(0, 0, -daysAgo).Format(time.DateOnly),
			current-daysAgo*growth, limit)
	}
	raw, err := proto.Marshal(&controlv1.Stats{RecursorCache: &controlv1.RecursorCacheStats{
		Enabled: true, Bytes: current, MaxBytes: limit,
	}})
	if err != nil {
		s.T.Fatal(err)
	}
	harness.PGExec(s.T, s.PGURL, `insert into engine_stats(engine_id, at, stats) values ($1, now(), $2)`, engineID, raw)
	// Only recursor_cache has enough history for model advice. The model supplies
	// no days or arithmetic: (22,700,000 - 18,500,000) / 350,000 = 12.
	const advice = "Raise the recursor cache budget before the working set grows past it."
	s.AI.ScriptJSON(s.T, "capacity_forecast", map[string]any{"forecasts": []any{
		map[string]any{"resource": "recursor_cache", "confidence": 0.66, "recommendation": advice},
	}})
	s.Admin.Must("POST", "/ai/agents/capacity_forecast/run", nil, nil, 202)
	harness.Eventually(s.T, 20*time.Second, func() error {
		var forecasts []struct {
			Subject  string `json:"subject"`
			Capacity struct {
				Current        float64 `json:"current_value"`
				Max            float64 `json:"max_value"`
				Growth         float64 `json:"growth_per_day"`
				Days           *int    `json:"days_remaining"`
				Points         int     `json:"points_analyzed"`
				Confidence     float64 `json:"confidence"`
				Recommendation string  `json:"recommendation"`
			} `json:"capacity"`
		}
		s.Admin.Must("GET", "/ai/forecasts?kind=capacity", nil, &forecasts, 200)
		for _, f := range forecasts {
			if f.Subject != "recursor_cache" {
				continue
			}
			c := f.Capacity
			if c.Current == current && c.Max == limit && c.Growth == growth && c.Days != nil && *c.Days == 12 &&
				c.Points == 7 && c.Confidence == 0.66 && c.Recommendation == advice {
				return nil
			}
			return fmt.Errorf("recursor capacity seed did not survive sampling/model validation: %+v", c)
		}
		return fmt.Errorf("capacity agent has not stored the recursor forecast")
	})
}
