package zone

import (
	"context"
	"errors"
	"fmt"
	"io"
	"strings"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/miekg/dns"

	"github.com/piwi3910/nexora/mgmt/internal/auth"
	"github.com/piwi3910/nexora/mgmt/internal/nzf"
	"github.com/piwi3910/nexora/mgmt/internal/store"
	"github.com/piwi3910/nexora/mgmt/internal/zonefile"
)

// MaxImportRecords bounds the records of one imported zone file.
const MaxImportRecords = 1000000

// ImportResult is the zone after an import and how many records it holds.
type ImportResult struct {
	Zone            *Zone
	RecordsImported int
}

// Import replaces every record and the SOA fields of primary zone zoneID (at revision) with the
// zone file content. The file's SOA serial is adopted when RFC 1982-greater than the current one.
func (s *Service) Import(ctx context.Context, actor auth.Actor, zoneID uuid.UUID, revision int64, content string) (*ImportResult, error) {
	current, err := s.GetZone(ctx, zoneID)
	if err != nil {
		return nil, err
	}
	res, err := zonefile.Parse(strings.NewReader(content), current.Name, zonefile.Options{AllowedTypes: ManagedTypes, MaxRecords: MaxImportRecords})
	if err != nil {
		ve := &ValidationError{Code: "zone_file_invalid", Message: err.Error()}
		var errs zonefile.Errors
		if errors.As(err, &errs) {
			for _, le := range errs {
				ve.Details = append(ve.Details, LineError{Line: le.Line, Message: le.Message})
			}
		}
		return nil, ve
	}
	if err := CheckSet(current.Name, res.Records); err != nil {
		return nil, err
	}
	soa := res.SOA
	out, err := s.Mutate(ctx, zoneID, func(tx pgx.Tx, z *Zone) (string, any, any, RebuildOptions, error) {
		// A producer catalog zone's records are generated by the catalog service (ErrCatalogManaged).
		if err := checkRecordsWritable(ctx, tx, z); err != nil {
			return "", nil, nil, RebuildOptions{}, err
		}
		if z.Revision != revision {
			return "", nil, nil, RebuildOptions{}, fmt.Errorf("zone revision %d is stale (current %d): %w", revision, z.Revision, store.ErrConflict)
		}
		if err := SetRecords(ctx, tx, z.ID, res.Records); err != nil {
			return "", nil, nil, RebuildOptions{}, err
		}
		defaultTTL := int64(z.DefaultTTL)
		if res.DefaultTTL > 0 {
			defaultTTL = int64(res.DefaultTTL)
		}
		if soa.Refresh == 0 || soa.Retry == 0 || soa.Expire == 0 {
			return "", nil, nil, RebuildOptions{}, invalid("invalid_soa", "soa refresh, retry and expire must be positive")
		}
		for _, v := range []uint32{soa.Refresh, soa.Retry, soa.Expire, soa.Minttl, soa.Hdr.Ttl} {
			if v > maxTTL {
				return "", nil, nil, RebuildOptions{}, invalid("invalid_soa", fmt.Sprintf("soa timer %d exceeds %d", v, maxTTL))
			}
		}
		if _, err := tx.Exec(ctx, `UPDATE zones SET default_ttl = $2, soa_mname = $3, soa_rname = $4, soa_refresh = $5, soa_retry = $6,
			soa_expire = $7, soa_minimum = $8, soa_ttl = $9 WHERE id = $1`, z.ID, defaultTTL, strings.ToLower(soa.Ns), strings.ToLower(soa.Mbox),
			int64(soa.Refresh), int64(soa.Retry), int64(soa.Expire), int64(soa.Minttl), int64(soa.Hdr.Ttl)); err != nil {
			return "", nil, nil, RebuildOptions{}, err
		}
		serial := soa.Serial
		after := map[string]any{"records": len(res.Records), "soa_serial": serial}
		return "importZoneFile", map[string]any{"revision": z.Revision, "serial": z.Serial}, after, RebuildOptions{Serial: &serial}, nil
	}, actor)
	if err != nil {
		return nil, err
	}
	return &ImportResult{Zone: out, RecordsImported: len(res.Records)}, nil
}

// ExportTo writes zone zoneID as a BIND master file to w, streaming records from one read-only
// snapshot: the SOA from the zone row, then the apex records, then owners lowercase byte-wise,
// then type and RDATA.
func (s *Service) ExportTo(ctx context.Context, zoneID uuid.UUID, w io.Writer) error {
	tx, err := s.Store.Pool.BeginTx(ctx, pgx.TxOptions{IsoLevel: pgx.RepeatableRead, AccessMode: pgx.ReadOnly})
	if err != nil {
		return store.MapError(err)
	}
	defer tx.Rollback(ctx) //nolint:errcheck // read-only
	z, err := loadZone(ctx, tx, zoneID, false)
	if err != nil {
		return err
	}
	zw := zonefile.NewWriter(w, z.Name, z.DefaultTTL)
	if err := zw.SOA(soaRR(z)); err != nil {
		return err
	}
	rows, err := tx.Query(ctx, `SELECT owner, rtype, ttl, rdata_wire FROM zone_records WHERE zone_id = $1
		ORDER BY lower(owner) <> lower($2), lower(owner) COLLATE "C", rtype, rdata_wire`, zoneID, z.Name)
	if err != nil {
		return store.MapError(err)
	}
	defer rows.Close()
	owner := make([]byte, 256)
	for rows.Next() {
		var name string
		var rtype int32
		var ttl int64
		var rdata []byte
		if err := rows.Scan(&name, &rtype, &ttl, &rdata); err != nil {
			return store.MapError(err)
		}
		n, err := dns.PackDomainName(name, owner, 0, nil, false)
		if err != nil {
			return fmt.Errorf("record owner %q: %w", name, err)
		}
		rr, err := nzf.ToRR(nzf.Record{Owner: owner[:n], Type: uint16(rtype), Class: dns.ClassINET, TTL: uint32(ttl), RData: rdata})
		if err != nil {
			return fmt.Errorf("record %s %d: %w", name, rtype, err)
		}
		if err := zw.Record(rr); err != nil {
			return err
		}
	}
	if err := rows.Err(); err != nil {
		return store.MapError(err)
	}
	return zw.Flush()
}
