package zone

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/miekg/dns"
)

// ManagedTypes are the record types operators may write; SOA lives on the zone row and DNSSEC
// types are generated by the signer.
var ManagedTypes = map[uint16]bool{
	dns.TypeA: true, dns.TypeAAAA: true, dns.TypeCNAME: true, dns.TypeDNAME: true, dns.TypeMX: true,
	dns.TypeNS: true, dns.TypePTR: true, dns.TypeSRV: true, dns.TypeTXT: true, dns.TypeCAA: true,
	dns.TypeSSHFP: true, dns.TypeTLSA: true, dns.TypeHTTPS: true, dns.TypeSVCB: true, dns.TypeDS: true,
	dns.TypeNAPTR: true, dns.TypeLOC: true,
}

// Signer signs the served RR set of DNSSEC-enabled zones (Task 12). Unsigned zones skip it.
type Signer interface {
	Sign(ctx context.Context, tx pgx.Tx, z *Zone, rrs []dns.RR, now time.Time) (served []dns.RR, err error)
	ResignSOA(ctx context.Context, tx pgx.Tx, z *Zone, served []dns.RR, now time.Time) ([]dns.RR, error)
}

// SOA holds the zone's SOA fields except the serial, which lives on Zone.
type SOA struct {
	MName, RName                         string
	Refresh, Retry, Expire, Minimum, TTL uint32
}

// Endpoint is a transfer peer: an "ip:port" address with an optional TSIG key.
type Endpoint struct {
	Address   string     `json:"address"`
	TSIGKeyID *uuid.UUID `json:"tsig_key_id"`
}

// Zone is one hosted zone row.
type Zone struct {
	ID                 uuid.UUID
	EngineGroupID      *uuid.UUID // nil: served by every engine group
	Name, Kind         string
	Revision           int64
	Serial             uint32
	DefaultTTL         uint32
	SOA                SOA
	TransferAllowCIDRs []netip.Prefix
	TransferTSIGKeyID  *uuid.UUID
	Notify             []Endpoint
	UpdateTSIGKeyIDs   []uuid.UUID
	Primaries          []Endpoint
	CurrentSeq         int64
	ImageSeq           int64
	Loaded, Expired    bool
	LastRefreshAt      *time.Time
	LastSuccessAt      *time.Time
	NextRefreshAt      *time.Time
	ExpiresAt          *time.Time
	LastError          string
	LastTrigger        string
	DNSSECEnabled      bool
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

// Record is one stored resource record; Data is the RDATA in presentation form.
type Record struct {
	ID       uuid.UUID
	ZoneID   uuid.UUID
	Name     string
	Type     string
	TTL      uint32
	Data     string
	Revision int64
}

// CreateZoneInput creates a primary (Nameservers) or secondary (Primaries) zone.
type CreateZoneInput struct {
	Name, Kind       string
	DefaultTTL       uint32
	SOA              SOA
	Nameservers      []string
	Primaries        []Endpoint
	Transfer         TransferInput
	Notify           []Endpoint
	UpdateTSIGKeyIDs []uuid.UUID
	// EngineGroupID scopes the zone to one engine group (nil: served by every group).
	EngineGroupID *uuid.UUID
}

// TransferInput is the outgoing transfer policy.
type TransferInput struct {
	AllowCIDRs []string
	TSIGKeyID  *uuid.UUID
}

// UpdateZoneInput changes the provided fields of the zone at Revision.
type UpdateZoneInput struct {
	Revision         int64
	DefaultTTL       *uint32
	SOA              *SOA
	Primaries        *[]Endpoint
	Transfer         *TransferInput
	Notify           *[]Endpoint
	UpdateTSIGKeyIDs *[]uuid.UUID
}

// RecordInput is one record as written by an operator; Name is absolute.
type RecordInput struct {
	Name, Type string
	TTL        uint32
	Data       string
}

// RebuildOptions steer Rebuild: Serial proposes a serial (adopted when RFC 1982-greater, always
// for secondaries); Force writes a new version even without changes.
type RebuildOptions struct {
	Serial *uint32
	Force  bool
}
