// Package mgmtapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package mgmtapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for EngineGroupRolloutStrategy.
const (
	EngineGroupRolloutStrategyAllAtOnce EngineGroupRolloutStrategy = "all_at_once"
	EngineGroupRolloutStrategyCanary    EngineGroupRolloutStrategy = "canary"
)

// Valid indicates whether the value is a known member of the EngineGroupRolloutStrategy enum.
func (e EngineGroupRolloutStrategy) Valid() bool {
	switch e {
	case EngineGroupRolloutStrategyAllAtOnce:
		return true
	case EngineGroupRolloutStrategyCanary:
		return true
	default:
		return false
	}
}

// Defines values for EngineGroupUpstreamMode.
const (
	EngineGroupUpstreamModeInherit  EngineGroupUpstreamMode = "inherit"
	EngineGroupUpstreamModeOverride EngineGroupUpstreamMode = "override"
)

// Valid indicates whether the value is a known member of the EngineGroupUpstreamMode enum.
func (e EngineGroupUpstreamMode) Valid() bool {
	switch e {
	case EngineGroupUpstreamModeInherit:
		return true
	case EngineGroupUpstreamModeOverride:
		return true
	default:
		return false
	}
}

// Defines values for EngineGroupInputRolloutStrategy.
const (
	EngineGroupInputRolloutStrategyAllAtOnce EngineGroupInputRolloutStrategy = "all_at_once"
	EngineGroupInputRolloutStrategyCanary    EngineGroupInputRolloutStrategy = "canary"
)

// Valid indicates whether the value is a known member of the EngineGroupInputRolloutStrategy enum.
func (e EngineGroupInputRolloutStrategy) Valid() bool {
	switch e {
	case EngineGroupInputRolloutStrategyAllAtOnce:
		return true
	case EngineGroupInputRolloutStrategyCanary:
		return true
	default:
		return false
	}
}

// Defines values for EngineGroupInputUpstreamMode.
const (
	EngineGroupInputUpstreamModeInherit  EngineGroupInputUpstreamMode = "inherit"
	EngineGroupInputUpstreamModeOverride EngineGroupInputUpstreamMode = "override"
)

// Valid indicates whether the value is a known member of the EngineGroupInputUpstreamMode enum.
func (e EngineGroupInputUpstreamMode) Valid() bool {
	switch e {
	case EngineGroupInputUpstreamModeInherit:
		return true
	case EngineGroupInputUpstreamModeOverride:
		return true
	default:
		return false
	}
}

// Defines values for EngineGroupUpdateRolloutStrategy.
const (
	EngineGroupUpdateRolloutStrategyAllAtOnce EngineGroupUpdateRolloutStrategy = "all_at_once"
	EngineGroupUpdateRolloutStrategyCanary    EngineGroupUpdateRolloutStrategy = "canary"
)

// Valid indicates whether the value is a known member of the EngineGroupUpdateRolloutStrategy enum.
func (e EngineGroupUpdateRolloutStrategy) Valid() bool {
	switch e {
	case EngineGroupUpdateRolloutStrategyAllAtOnce:
		return true
	case EngineGroupUpdateRolloutStrategyCanary:
		return true
	default:
		return false
	}
}

// Defines values for EngineGroupUpdateUpstreamMode.
const (
	EngineGroupUpdateUpstreamModeInherit  EngineGroupUpdateUpstreamMode = "inherit"
	EngineGroupUpdateUpstreamModeOverride EngineGroupUpdateUpstreamMode = "override"
)

// Valid indicates whether the value is a known member of the EngineGroupUpdateUpstreamMode enum.
func (e EngineGroupUpdateUpstreamMode) Valid() bool {
	switch e {
	case EngineGroupUpdateUpstreamModeInherit:
		return true
	case EngineGroupUpdateUpstreamModeOverride:
		return true
	default:
		return false
	}
}

// Defines values for HealthDatabase.
const (
	HealthDatabaseOk          HealthDatabase = "ok"
	HealthDatabaseUnavailable HealthDatabase = "unavailable"
)

// Valid indicates whether the value is a known member of the HealthDatabase enum.
func (e HealthDatabase) Valid() bool {
	switch e {
	case HealthDatabaseOk:
		return true
	case HealthDatabaseUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	HealthStatusDegraded HealthStatus = "degraded"
	HealthStatusOk       HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case HealthStatusDegraded:
		return true
	case HealthStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for JoinTokenState.
const (
	Active    JoinTokenState = "active"
	Exhausted JoinTokenState = "exhausted"
	Expired   JoinTokenState = "expired"
	Revoked   JoinTokenState = "revoked"
)

// Valid indicates whether the value is a known member of the JoinTokenState enum.
func (e JoinTokenState) Valid() bool {
	switch e {
	case Active:
		return true
	case Exhausted:
		return true
	case Expired:
		return true
	case Revoked:
		return true
	default:
		return false
	}
}

// Defines values for RolloutKind.
const (
	Change    RolloutKind = "change"
	Republish RolloutKind = "republish"
	Rollback  RolloutKind = "rollback"
)

// Valid indicates whether the value is a known member of the RolloutKind enum.
func (e RolloutKind) Valid() bool {
	switch e {
	case Change:
		return true
	case Republish:
		return true
	case Rollback:
		return true
	default:
		return false
	}
}

// Defines values for RolloutStrategy.
const (
	RolloutStrategyAllAtOnce RolloutStrategy = "all_at_once"
	RolloutStrategyCanary    RolloutStrategy = "canary"
)

// Valid indicates whether the value is a known member of the RolloutStrategy enum.
func (e RolloutStrategy) Valid() bool {
	switch e {
	case RolloutStrategyAllAtOnce:
		return true
	case RolloutStrategyCanary:
		return true
	default:
		return false
	}
}

// Defines values for RolloutState.
const (
	RolloutStateCanary     RolloutState = "canary"
	RolloutStateCompleted  RolloutState = "completed"
	RolloutStateHalted     RolloutState = "halted"
	RolloutStatePending    RolloutState = "pending"
	RolloutStateRolledBack RolloutState = "rolled_back"
	RolloutStateRolling    RolloutState = "rolling"
	RolloutStateSuperseded RolloutState = "superseded"
	RolloutStateVerifying  RolloutState = "verifying"
)

// Valid indicates whether the value is a known member of the RolloutState enum.
func (e RolloutState) Valid() bool {
	switch e {
	case RolloutStateCanary:
		return true
	case RolloutStateCompleted:
		return true
	case RolloutStateHalted:
		return true
	case RolloutStatePending:
		return true
	case RolloutStateRolledBack:
		return true
	case RolloutStateRolling:
		return true
	case RolloutStateSuperseded:
		return true
	case RolloutStateVerifying:
		return true
	default:
		return false
	}
}

// EngineGroup defines model for EngineGroup.
type EngineGroup struct {
	AckTimeoutSeconds   int                        `json:"ack_timeout_seconds"`
	ActiveRollout       *Rollout                   `json:"active_rollout,omitempty"`
	CanaryCount         int                        `json:"canary_count"`
	CanaryPercent       int                        `json:"canary_percent"`
	CreatedAt           time.Time                  `json:"created_at"`
	Description         string                     `json:"description"`
	EngineCount         int                        `json:"engine_count"`
	ExtraAclCidrs       []string                   `json:"extra_acl_cidrs"`
	FilterIndexMaxBytes int64                      `json:"filter_index_max_bytes"`
	HealthWindowSeconds int                        `json:"health_window_seconds"`
	Id                  openapi_types.UUID         `json:"id"`
	MaxServfailRatio    float32                    `json:"max_servfail_ratio"`
	Mdns                MdnsSettings               `json:"mdns"`
	MinHealthQueries    int                        `json:"min_health_queries"`
	Name                string                     `json:"name"`
	OtlpEndpoint        string                     `json:"otlp_endpoint"`
	Revision            int64                      `json:"revision"`
	RolloutStrategy     EngineGroupRolloutStrategy `json:"rollout_strategy"`
	RolloutsPaused      bool                       `json:"rollouts_paused"`
	StableVersion       *int64                     `json:"stable_version,omitempty"`
	UpdatedAt           time.Time                  `json:"updated_at"`
	UpstreamMode        EngineGroupUpstreamMode    `json:"upstream_mode"`
}

// EngineGroupRolloutStrategy defines model for EngineGroup.RolloutStrategy.
type EngineGroupRolloutStrategy string

// EngineGroupUpstreamMode defines model for EngineGroup.UpstreamMode.
type EngineGroupUpstreamMode string

// EngineGroupInput defines model for EngineGroupInput.
type EngineGroupInput struct {
	AckTimeoutSeconds *int      `json:"ack_timeout_seconds,omitempty"`
	CanaryCount       *int      `json:"canary_count,omitempty"`
	CanaryPercent     *int      `json:"canary_percent,omitempty"`
	Description       *string   `json:"description,omitempty"`
	ExtraAclCidrs     *[]string `json:"extra_acl_cidrs,omitempty"`

	// FilterIndexMaxBytes filter index memory cap of this group's engines; 0 = engine default (50% of the cgroup memory limit, else 512 MiB), otherwise at least 16777216
	FilterIndexMaxBytes *int64                           `json:"filter_index_max_bytes,omitempty"`
	HealthWindowSeconds *int                             `json:"health_window_seconds,omitempty"`
	MaxServfailRatio    *float32                         `json:"max_servfail_ratio,omitempty"`
	Mdns                *MdnsSettings                    `json:"mdns,omitempty"`
	MinHealthQueries    *int                             `json:"min_health_queries,omitempty"`
	Name                string                           `json:"name"`
	OtlpEndpoint        *string                          `json:"otlp_endpoint,omitempty"`
	RolloutStrategy     *EngineGroupInputRolloutStrategy `json:"rollout_strategy,omitempty"`
	UpstreamMode        *EngineGroupInputUpstreamMode    `json:"upstream_mode,omitempty"`
}

// EngineGroupInputRolloutStrategy defines model for EngineGroupInput.RolloutStrategy.
type EngineGroupInputRolloutStrategy string

// EngineGroupInputUpstreamMode defines model for EngineGroupInput.UpstreamMode.
type EngineGroupInputUpstreamMode string

// EngineGroupUpdate defines model for EngineGroupUpdate.
type EngineGroupUpdate struct {
	AckTimeoutSeconds *int      `json:"ack_timeout_seconds,omitempty"`
	CanaryCount       *int      `json:"canary_count,omitempty"`
	CanaryPercent     *int      `json:"canary_percent,omitempty"`
	Description       *string   `json:"description,omitempty"`
	ExtraAclCidrs     *[]string `json:"extra_acl_cidrs,omitempty"`

	// FilterIndexMaxBytes filter index memory cap of this group's engines; 0 = engine default (50% of the cgroup memory limit, else 512 MiB), otherwise at least 16777216
	FilterIndexMaxBytes *int64                            `json:"filter_index_max_bytes,omitempty"`
	HealthWindowSeconds *int                              `json:"health_window_seconds,omitempty"`
	MaxServfailRatio    *float32                          `json:"max_servfail_ratio,omitempty"`
	Mdns                *MdnsSettings                     `json:"mdns,omitempty"`
	MinHealthQueries    *int                              `json:"min_health_queries,omitempty"`
	Name                string                            `json:"name"`
	OtlpEndpoint        *string                           `json:"otlp_endpoint,omitempty"`
	Revision            int64                             `json:"revision"`
	RolloutStrategy     *EngineGroupUpdateRolloutStrategy `json:"rollout_strategy,omitempty"`
	UpstreamMode        *EngineGroupUpdateUpstreamMode    `json:"upstream_mode,omitempty"`
}

// EngineGroupUpdateRolloutStrategy defines model for EngineGroupUpdate.RolloutStrategy.
type EngineGroupUpdateRolloutStrategy string

// EngineGroupUpdateUpstreamMode defines model for EngineGroupUpdate.UpstreamMode.
type EngineGroupUpdateUpstreamMode string

// Error defines model for Error.
type Error struct {
	Code string `json:"code"`

	// Details Per-line problems of submitted zone data; for license_acknowledgement_required one entry per source (line 0, message "<source key>: <notice>").
	Details *[]struct {
		Line    int    `json:"line"`
		Message string `json:"message"`
	} `json:"details,omitempty"`
	Message string `json:"message"`
}

// Health defines model for Health.
type Health struct {
	Database HealthDatabase `json:"database"`
	Status   HealthStatus   `json:"status"`
	Version  string         `json:"version"`
}

// HealthDatabase defines model for Health.Database.
type HealthDatabase string

// HealthStatus defines model for Health.Status.
type HealthStatus string

// JoinToken defines model for JoinToken.
type JoinToken struct {
	CreatedAt       time.Time          `json:"created_at"`
	CreatedBy       string             `json:"created_by"`
	EngineGroupId   openapi_types.UUID `json:"engine_group_id"`
	EngineGroupName string             `json:"engine_group_name"`
	ExpiresAt       time.Time          `json:"expires_at"`
	Id              openapi_types.UUID `json:"id"`
	Labels          map[string]string  `json:"labels"`
	MaxUses         *int               `json:"max_uses,omitempty"`
	Name            string             `json:"name"`
	RevokedAt       *time.Time         `json:"revoked_at,omitempty"`
	State           JoinTokenState     `json:"state"`
	Uses            int                `json:"uses"`
}

// JoinTokenState defines model for JoinToken.State.
type JoinTokenState string

// JoinTokenCreate defines model for JoinTokenCreate.
type JoinTokenCreate struct {
	EngineGroupId *openapi_types.UUID `json:"engine_group_id,omitempty"`
	Labels        *map[string]string  `json:"labels,omitempty"`
	MaxUses       *int                `json:"max_uses,omitempty"`
	Name          string              `json:"name"`
	TtlSeconds    int                 `json:"ttl_seconds"`
}

// JoinTokenCreated defines model for JoinTokenCreated.
type JoinTokenCreated struct {
	JoinToken JoinToken `json:"join_token"`
	Token     string    `json:"token"`
}

// MdnsSettings defines model for MdnsSettings.
type MdnsSettings struct {
	Enabled           bool     `json:"enabled"`
	Interfaces        []string `json:"interfaces"`
	Reflect           bool     `json:"reflect"`
	ReflectInterfaces []string `json:"reflect_interfaces"`
	TimeoutMs         int      `json:"timeout_ms"`
}

// Rollout defines model for Rollout.
type Rollout struct {
	CanaryEngineIds []openapi_types.UUID `json:"canary_engine_ids"`
	CreatedAt       time.Time            `json:"created_at"`
	CreatedBy       string               `json:"created_by"`
	EngineGroupId   openapi_types.UUID   `json:"engine_group_id"`
	EngineGroupName string               `json:"engine_group_name"`
	FinishedAt      *time.Time           `json:"finished_at,omitempty"`
	FromVersion     *int64               `json:"from_version,omitempty"`
	HaltReason      string               `json:"halt_reason"`
	Id              openapi_types.UUID   `json:"id"`
	Kind            RolloutKind          `json:"kind"`
	PhaseStartedAt  *time.Time           `json:"phase_started_at,omitempty"`
	Progress        struct {
		Applied  int `json:"applied"`
		Rejected int `json:"rejected"`
		Total    int `json:"total"`
	} `json:"progress"`
	State    RolloutState    `json:"state"`
	Strategy RolloutStrategy `json:"strategy"`
	Version  int64           `json:"version"`
}

// RolloutKind defines model for Rollout.Kind.
type RolloutKind string

// RolloutStrategy defines model for Rollout.Strategy.
type RolloutStrategy string

// RolloutState defines model for RolloutState.
type RolloutState string

// SetupStatus defines model for SetupStatus.
type SetupStatus struct {
	Required bool `json:"required"`
}

// Id defines model for Id.
type Id = openapi_types.UUID

// Revision defines model for Revision.
type Revision = int64

// DeleteEngineGroupParams defines parameters for DeleteEngineGroup.
type DeleteEngineGroupParams struct {
	Revision Revision `form:"revision" json:"revision"`
}

// CreateEngineGroupJSONRequestBody defines body for CreateEngineGroup for application/json ContentType.
type CreateEngineGroupJSONRequestBody = EngineGroupInput

// UpdateEngineGroupJSONRequestBody defines body for UpdateEngineGroup for application/json ContentType.
type UpdateEngineGroupJSONRequestBody = EngineGroupUpdate

// CreateJoinTokenJSONRequestBody defines body for CreateJoinToken for application/json ContentType.
type CreateJoinTokenJSONRequestBody = JoinTokenCreate

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// rawClient which conforms to the OpenAPI3 specification for this service.
type rawClient struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*rawClient) error

// Creates a new rawClient, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*rawClient, error) {
	// create a client with sane default values
	client := rawClient{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *rawClient) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *rawClient) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// ListEngineGroups performs a GET /engine-groups (the `ListEngineGroups` operationId) request.
	ListEngineGroups(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateEngineGroupWithBody performs a POST /engine-groups (the `CreateEngineGroup` operationId) request,
	// with any type of body and a specified content type.
	CreateEngineGroupWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateEngineGroup performs a POST /engine-groups (the `CreateEngineGroup` operationId) request.
	// Takes a body of the `application/json` content type.
	CreateEngineGroup(ctx context.Context, body CreateEngineGroupJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteEngineGroup performs a DELETE /engine-groups/{id} (the `DeleteEngineGroup` operationId) request.
	DeleteEngineGroup(ctx context.Context, id Id, params *DeleteEngineGroupParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetEngineGroup performs a GET /engine-groups/{id} (the `GetEngineGroup` operationId) request.
	GetEngineGroup(ctx context.Context, id Id, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateEngineGroupWithBody performs a PUT /engine-groups/{id} (the `UpdateEngineGroup` operationId) request,
	// with any type of body and a specified content type.
	UpdateEngineGroupWithBody(ctx context.Context, id Id, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateEngineGroup performs a PUT /engine-groups/{id} (the `UpdateEngineGroup` operationId) request.
	// Takes a body of the `application/json` content type.
	UpdateEngineGroup(ctx context.Context, id Id, body UpdateEngineGroupJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHealth performs a GET /health (the `GetHealth` operationId) request.
	GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListJoinTokens performs a GET /join-tokens (the `ListJoinTokens` operationId) request.
	ListJoinTokens(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateJoinTokenWithBody performs a POST /join-tokens (the `CreateJoinToken` operationId) request,
	// with any type of body and a specified content type.
	CreateJoinTokenWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateJoinToken performs a POST /join-tokens (the `CreateJoinToken` operationId) request.
	// Takes a body of the `application/json` content type.
	CreateJoinToken(ctx context.Context, body CreateJoinTokenJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RevokeJoinToken performs a DELETE /join-tokens/{id} (the `RevokeJoinToken` operationId) request.
	RevokeJoinToken(ctx context.Context, id Id, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetSetupStatus performs a GET /setup (the `GetSetupStatus` operationId) request.
	GetSetupStatus(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// ListEngineGroups performs a GET /engine-groups (the `ListEngineGroups` operationId) request.
func (c *rawClient) ListEngineGroups(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListEngineGroupsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateEngineGroupWithBody performs a POST /engine-groups (the `CreateEngineGroup` operationId) request,
// with any type of body and a specified content type.
func (c *rawClient) CreateEngineGroupWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateEngineGroupRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateEngineGroup performs a POST /engine-groups (the `CreateEngineGroup` operationId) request.
// Takes a body of the `application/json` content type.
func (c *rawClient) CreateEngineGroup(ctx context.Context, body CreateEngineGroupJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateEngineGroupRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeleteEngineGroup performs a DELETE /engine-groups/{id} (the `DeleteEngineGroup` operationId) request.
func (c *rawClient) DeleteEngineGroup(ctx context.Context, id Id, params *DeleteEngineGroupParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteEngineGroupRequest(c.Server, id, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetEngineGroup performs a GET /engine-groups/{id} (the `GetEngineGroup` operationId) request.
func (c *rawClient) GetEngineGroup(ctx context.Context, id Id, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetEngineGroupRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UpdateEngineGroupWithBody performs a PUT /engine-groups/{id} (the `UpdateEngineGroup` operationId) request,
// with any type of body and a specified content type.
func (c *rawClient) UpdateEngineGroupWithBody(ctx context.Context, id Id, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateEngineGroupRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UpdateEngineGroup performs a PUT /engine-groups/{id} (the `UpdateEngineGroup` operationId) request.
// Takes a body of the `application/json` content type.
func (c *rawClient) UpdateEngineGroup(ctx context.Context, id Id, body UpdateEngineGroupJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateEngineGroupRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetHealth performs a GET /health (the `GetHealth` operationId) request.
func (c *rawClient) GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ListJoinTokens performs a GET /join-tokens (the `ListJoinTokens` operationId) request.
func (c *rawClient) ListJoinTokens(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListJoinTokensRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateJoinTokenWithBody performs a POST /join-tokens (the `CreateJoinToken` operationId) request,
// with any type of body and a specified content type.
func (c *rawClient) CreateJoinTokenWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateJoinTokenRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateJoinToken performs a POST /join-tokens (the `CreateJoinToken` operationId) request.
// Takes a body of the `application/json` content type.
func (c *rawClient) CreateJoinToken(ctx context.Context, body CreateJoinTokenJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateJoinTokenRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// RevokeJoinToken performs a DELETE /join-tokens/{id} (the `RevokeJoinToken` operationId) request.
func (c *rawClient) RevokeJoinToken(ctx context.Context, id Id, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRevokeJoinTokenRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetSetupStatus performs a GET /setup (the `GetSetupStatus` operationId) request.
func (c *rawClient) GetSetupStatus(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetSetupStatusRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListEngineGroupsRequest constructs an http.Request for the ListEngineGroups method
func NewListEngineGroupsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/engine-groups")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateEngineGroupRequest calls the generic CreateEngineGroup builder with application/json body
func NewCreateEngineGroupRequest(server string, body CreateEngineGroupJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateEngineGroupRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateEngineGroupRequestWithBody constructs an http.Request for the CreateEngineGroup method, with any body, and a specified content type
func NewCreateEngineGroupRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/engine-groups")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteEngineGroupRequest constructs an http.Request for the DeleteEngineGroup method
func NewDeleteEngineGroupRequest(server string, id Id, params *DeleteEngineGroupParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/engine-groups/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "revision", params.Revision, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int64"}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetEngineGroupRequest constructs an http.Request for the GetEngineGroup method
func NewGetEngineGroupRequest(server string, id Id) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/engine-groups/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateEngineGroupRequest calls the generic UpdateEngineGroup builder with application/json body
func NewUpdateEngineGroupRequest(server string, id Id, body UpdateEngineGroupJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateEngineGroupRequestWithBody(server, id, "application/json", bodyReader)
}

// NewUpdateEngineGroupRequestWithBody constructs an http.Request for the UpdateEngineGroup method, with any body, and a specified content type
func NewUpdateEngineGroupRequestWithBody(server string, id Id, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/engine-groups/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetHealthRequest constructs an http.Request for the GetHealth method
func NewGetHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListJoinTokensRequest constructs an http.Request for the ListJoinTokens method
func NewListJoinTokensRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/join-tokens")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateJoinTokenRequest calls the generic CreateJoinToken builder with application/json body
func NewCreateJoinTokenRequest(server string, body CreateJoinTokenJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateJoinTokenRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateJoinTokenRequestWithBody constructs an http.Request for the CreateJoinToken method, with any body, and a specified content type
func NewCreateJoinTokenRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/join-tokens")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewRevokeJoinTokenRequest constructs an http.Request for the RevokeJoinToken method
func NewRevokeJoinTokenRequest(server string, id Id) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/join-tokens/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetSetupStatusRequest constructs an http.Request for the GetSetupStatus method
func NewGetSetupStatusRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/setup")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *rawClient) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *rawClient) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// ListEngineGroupsWithResponse performs a GET /engine-groups (the `ListEngineGroups` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	ListEngineGroupsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListEngineGroupsResponse, error)

	// CreateEngineGroupWithBodyWithResponse performs a POST /engine-groups (the `CreateEngineGroup` operationId) request,
	// with any type of body and a specified content type.
	//
	// Returns a wrapper object for the known response body format(s).
	CreateEngineGroupWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateEngineGroupResponse, error)

	// CreateEngineGroupWithResponse performs a POST /engine-groups (the `CreateEngineGroup` operationId) request.
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	CreateEngineGroupWithResponse(ctx context.Context, body CreateEngineGroupJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateEngineGroupResponse, error)

	// DeleteEngineGroupWithResponse performs a DELETE /engine-groups/{id} (the `DeleteEngineGroup` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	DeleteEngineGroupWithResponse(ctx context.Context, id Id, params *DeleteEngineGroupParams, reqEditors ...RequestEditorFn) (*DeleteEngineGroupResponse, error)

	// GetEngineGroupWithResponse performs a GET /engine-groups/{id} (the `GetEngineGroup` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	GetEngineGroupWithResponse(ctx context.Context, id Id, reqEditors ...RequestEditorFn) (*GetEngineGroupResponse, error)

	// UpdateEngineGroupWithBodyWithResponse performs a PUT /engine-groups/{id} (the `UpdateEngineGroup` operationId) request,
	// with any type of body and a specified content type.
	//
	// Returns a wrapper object for the known response body format(s).
	UpdateEngineGroupWithBodyWithResponse(ctx context.Context, id Id, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateEngineGroupResponse, error)

	// UpdateEngineGroupWithResponse performs a PUT /engine-groups/{id} (the `UpdateEngineGroup` operationId) request.
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	UpdateEngineGroupWithResponse(ctx context.Context, id Id, body UpdateEngineGroupJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateEngineGroupResponse, error)

	// GetHealthWithResponse performs a GET /health (the `GetHealth` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error)

	// ListJoinTokensWithResponse performs a GET /join-tokens (the `ListJoinTokens` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	ListJoinTokensWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListJoinTokensResponse, error)

	// CreateJoinTokenWithBodyWithResponse performs a POST /join-tokens (the `CreateJoinToken` operationId) request,
	// with any type of body and a specified content type.
	//
	// Returns a wrapper object for the known response body format(s).
	CreateJoinTokenWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateJoinTokenResponse, error)

	// CreateJoinTokenWithResponse performs a POST /join-tokens (the `CreateJoinToken` operationId) request.
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	CreateJoinTokenWithResponse(ctx context.Context, body CreateJoinTokenJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateJoinTokenResponse, error)

	// RevokeJoinTokenWithResponse performs a DELETE /join-tokens/{id} (the `RevokeJoinToken` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	RevokeJoinTokenWithResponse(ctx context.Context, id Id, reqEditors ...RequestEditorFn) (*RevokeJoinTokenResponse, error)

	// GetSetupStatusWithResponse performs a GET /setup (the `GetSetupStatus` operationId) request.
	//
	// Returns a wrapper object for the known response body format(s).
	GetSetupStatusWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetSetupStatusResponse, error)
}

type ListEngineGroupsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *[]EngineGroup
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListEngineGroupsResponse) GetJSON200() *[]EngineGroup {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r ListEngineGroupsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListEngineGroupsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListEngineGroupsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListEngineGroupsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreateEngineGroupResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *EngineGroup
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Error
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r CreateEngineGroupResponse) GetJSON201() *EngineGroup {
	return r.JSON201
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r CreateEngineGroupResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r CreateEngineGroupResponse) GetJSON409() *Error {
	return r.JSON409
}

// GetBody returns the raw response body bytes
func (r CreateEngineGroupResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CreateEngineGroupResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateEngineGroupResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateEngineGroupResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteEngineGroupResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Error
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r DeleteEngineGroupResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r DeleteEngineGroupResponse) GetJSON409() *Error {
	return r.JSON409
}

// GetBody returns the raw response body bytes
func (r DeleteEngineGroupResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DeleteEngineGroupResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteEngineGroupResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteEngineGroupResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetEngineGroupResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *EngineGroup
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetEngineGroupResponse) GetJSON200() *EngineGroup {
	return r.JSON200
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetEngineGroupResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r GetEngineGroupResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetEngineGroupResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetEngineGroupResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetEngineGroupResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type UpdateEngineGroupResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *EngineGroup
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r UpdateEngineGroupResponse) GetJSON200() *EngineGroup {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r UpdateEngineGroupResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r UpdateEngineGroupResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r UpdateEngineGroupResponse) GetJSON409() *Error {
	return r.JSON409
}

// GetBody returns the raw response body bytes
func (r UpdateEngineGroupResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r UpdateEngineGroupResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateEngineGroupResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r UpdateEngineGroupResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Health
	// JSON503 the response for an HTTP 503 `application/json` response
	JSON503 *Health
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetHealthResponse) GetJSON200() *Health {
	return r.JSON200
}

// GetJSON503 returns the response for an HTTP 503 `application/json` response
func (r GetHealthResponse) GetJSON503() *Health {
	return r.JSON503
}

// GetBody returns the raw response body bytes
func (r GetHealthResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetHealthResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListJoinTokensResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *[]JoinToken
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListJoinTokensResponse) GetJSON200() *[]JoinToken {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r ListJoinTokensResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListJoinTokensResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListJoinTokensResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListJoinTokensResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreateJoinTokenResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *JoinTokenCreated
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON422 the response for an HTTP 422 `application/json` response
	JSON422 *Error
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r CreateJoinTokenResponse) GetJSON201() *JoinTokenCreated {
	return r.JSON201
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r CreateJoinTokenResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON422 returns the response for an HTTP 422 `application/json` response
func (r CreateJoinTokenResponse) GetJSON422() *Error {
	return r.JSON422
}

// GetBody returns the raw response body bytes
func (r CreateJoinTokenResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CreateJoinTokenResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateJoinTokenResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateJoinTokenResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type RevokeJoinTokenResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r RevokeJoinTokenResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r RevokeJoinTokenResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r RevokeJoinTokenResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RevokeJoinTokenResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r RevokeJoinTokenResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetSetupStatusResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *SetupStatus
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetSetupStatusResponse) GetJSON200() *SetupStatus {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GetSetupStatusResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetSetupStatusResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetSetupStatusResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetSetupStatusResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ListEngineGroupsWithResponse performs a GET /engine-groups (the `ListEngineGroups` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) ListEngineGroupsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListEngineGroupsResponse, error) {
	rsp, err := c.ListEngineGroups(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListEngineGroupsResponse(rsp)
}

// CreateEngineGroupWithBodyWithResponse performs a POST /engine-groups (the `CreateEngineGroup` operationId) request,
// with any type of body and a specified content type.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) CreateEngineGroupWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateEngineGroupResponse, error) {
	rsp, err := c.CreateEngineGroupWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateEngineGroupResponse(rsp)
}

// CreateEngineGroupWithResponse performs a POST /engine-groups (the `CreateEngineGroup` operationId) request.
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) CreateEngineGroupWithResponse(ctx context.Context, body CreateEngineGroupJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateEngineGroupResponse, error) {
	rsp, err := c.CreateEngineGroup(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateEngineGroupResponse(rsp)
}

// DeleteEngineGroupWithResponse performs a DELETE /engine-groups/{id} (the `DeleteEngineGroup` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) DeleteEngineGroupWithResponse(ctx context.Context, id Id, params *DeleteEngineGroupParams, reqEditors ...RequestEditorFn) (*DeleteEngineGroupResponse, error) {
	rsp, err := c.DeleteEngineGroup(ctx, id, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteEngineGroupResponse(rsp)
}

// GetEngineGroupWithResponse performs a GET /engine-groups/{id} (the `GetEngineGroup` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) GetEngineGroupWithResponse(ctx context.Context, id Id, reqEditors ...RequestEditorFn) (*GetEngineGroupResponse, error) {
	rsp, err := c.GetEngineGroup(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetEngineGroupResponse(rsp)
}

// UpdateEngineGroupWithBodyWithResponse performs a PUT /engine-groups/{id} (the `UpdateEngineGroup` operationId) request,
// with any type of body and a specified content type.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) UpdateEngineGroupWithBodyWithResponse(ctx context.Context, id Id, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateEngineGroupResponse, error) {
	rsp, err := c.UpdateEngineGroupWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateEngineGroupResponse(rsp)
}

// UpdateEngineGroupWithResponse performs a PUT /engine-groups/{id} (the `UpdateEngineGroup` operationId) request.
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) UpdateEngineGroupWithResponse(ctx context.Context, id Id, body UpdateEngineGroupJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateEngineGroupResponse, error) {
	rsp, err := c.UpdateEngineGroup(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateEngineGroupResponse(rsp)
}

// GetHealthWithResponse performs a GET /health (the `GetHealth` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error) {
	rsp, err := c.GetHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthResponse(rsp)
}

// ListJoinTokensWithResponse performs a GET /join-tokens (the `ListJoinTokens` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) ListJoinTokensWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListJoinTokensResponse, error) {
	rsp, err := c.ListJoinTokens(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListJoinTokensResponse(rsp)
}

// CreateJoinTokenWithBodyWithResponse performs a POST /join-tokens (the `CreateJoinToken` operationId) request,
// with any type of body and a specified content type.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) CreateJoinTokenWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateJoinTokenResponse, error) {
	rsp, err := c.CreateJoinTokenWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateJoinTokenResponse(rsp)
}

// CreateJoinTokenWithResponse performs a POST /join-tokens (the `CreateJoinToken` operationId) request.
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) CreateJoinTokenWithResponse(ctx context.Context, body CreateJoinTokenJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateJoinTokenResponse, error) {
	rsp, err := c.CreateJoinToken(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateJoinTokenResponse(rsp)
}

// RevokeJoinTokenWithResponse performs a DELETE /join-tokens/{id} (the `RevokeJoinToken` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) RevokeJoinTokenWithResponse(ctx context.Context, id Id, reqEditors ...RequestEditorFn) (*RevokeJoinTokenResponse, error) {
	rsp, err := c.RevokeJoinToken(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRevokeJoinTokenResponse(rsp)
}

// GetSetupStatusWithResponse performs a GET /setup (the `GetSetupStatus` operationId) request.
//
// Returns a wrapper object for the known response body format(s).
func (c *ClientWithResponses) GetSetupStatusWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetSetupStatusResponse, error) {
	rsp, err := c.GetSetupStatus(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetSetupStatusResponse(rsp)
}

// ParseListEngineGroupsResponse parses an HTTP response from a ListEngineGroupsWithResponse call
func ParseListEngineGroupsResponse(rsp *http.Response) (*ListEngineGroupsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListEngineGroupsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []EngineGroup
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCreateEngineGroupResponse parses an HTTP response from a CreateEngineGroupWithResponse call
func ParseCreateEngineGroupResponse(rsp *http.Response) (*CreateEngineGroupResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateEngineGroupResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest EngineGroup
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}

// ParseDeleteEngineGroupResponse parses an HTTP response from a DeleteEngineGroupWithResponse call
func ParseDeleteEngineGroupResponse(rsp *http.Response) (*DeleteEngineGroupResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteEngineGroupResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 204:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}

// ParseGetEngineGroupResponse parses an HTTP response from a GetEngineGroupWithResponse call
func ParseGetEngineGroupResponse(rsp *http.Response) (*GetEngineGroupResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetEngineGroupResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EngineGroup
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseUpdateEngineGroupResponse parses an HTTP response from a UpdateEngineGroupWithResponse call
func ParseUpdateEngineGroupResponse(rsp *http.Response) (*UpdateEngineGroupResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateEngineGroupResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest EngineGroup
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}

// ParseGetHealthResponse parses an HTTP response from a GetHealthWithResponse call
func ParseGetHealthResponse(rsp *http.Response) (*GetHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Health
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Health
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseListJoinTokensResponse parses an HTTP response from a ListJoinTokensWithResponse call
func ParseListJoinTokensResponse(rsp *http.Response) (*ListJoinTokensResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListJoinTokensResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []JoinToken
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCreateJoinTokenResponse parses an HTTP response from a CreateJoinTokenWithResponse call
func ParseCreateJoinTokenResponse(rsp *http.Response) (*CreateJoinTokenResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateJoinTokenResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest JoinTokenCreated
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseRevokeJoinTokenResponse parses an HTTP response from a RevokeJoinTokenWithResponse call
func ParseRevokeJoinTokenResponse(rsp *http.Response) (*RevokeJoinTokenResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RevokeJoinTokenResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 204:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetSetupStatusResponse parses an HTTP response from a GetSetupStatusWithResponse call
func ParseGetSetupStatusResponse(rsp *http.Response) (*GetSetupStatusResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetSetupStatusResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SetupStatus
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
